name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.50.2
        cache: true

    - name: Install dependencies
      run: pixi install --environment test

    - name: Run tests
      run: pixi run -e test pytest tests/ -v

    - name: Generate coverage report
      run: pixi run -e test pytest tests/ --cov=what_the_chat --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  package-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.50.2
        cache: true

    - name: Install dependencies
      run: pixi install

    - name: Test package installation
      run: |
        pixi run python -c 'import what_the_chat; print("Package import successful")'
        pixi run python -c 'from what_the_chat import DiscordPlatform, SlackPlatform, SummarizationService, ChatService; print("Main classes import successful")'
