name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pixi
      uses: prefix-dev/setup-pixi@v0.9.0
      with:
        pixi-version: v0.34.0

    - name: Install dependencies
      run: pixi install

    - name: Run tests
      run: pixi run -e test pytest tests/ -v --tb=short

    - name: Run tests with coverage
      run: pixi run -e test pytest tests/ --cov=what_the_chat --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
